### ISSUE TITLE
Write documentation on using {keyring} in Posit Workbench

### ISSUE THREAD

**Issue by terrymclaughlin** [Public-Health-Scotland/R-Resources#37]
@ciarag01 @rmccreath 

David Bailey highlighted that there is a contradiction between the Posit Workbench Acceptable Use Policy and being able to use the {keyring} package, which requires files to be saved in a user's home directory.  This issue suggests that documentation should be written to clarify this as acceptable use.

**Comment by ciarag01** [comment]
Good point! Does pandoc need to be included in this too?

https://scottish.sharepoint.com/sites/PHSRUserGroup/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPHSRUserGroup%2FShared%20Documents%2FTechnical%20Queries%2FPandoc%5Fv2%5FRStudio%5FServer%5FInstallation%2Epdf&parent=%2Fsites%2FPHSRUserGroup%2FShared%20Documents%2FTechnical%20Queries&p=true&ga=1

**Comment by terrymclaughlin** [comment]
@ciarag01 

I've double checked the version of pandoc installed alongside Posit Workbench:

```
> rmarkdown::find_pandoc()
$version
[1] ‘2.18’

$dir
[1] "/usr/lib/rstudio-server/bin/pandoc"
```

So, users shouldn't need to install pandoc manually.
